### ISSUE TITLE
Treeview selections are not shown

### ISSUE THREAD

**Issue by Akuli** [TkinterEP/ttkthemes#15]
Ttk treeviews work very well with some themes, like alt...

![alt](https://user-images.githubusercontent.com/18505570/39081211-16ab6234-4546-11e8-803d-d03f1ac26c0f.png)

...while they really fuck up with other themes. Here's black:

![black](https://user-images.githubusercontent.com/18505570/39081214-22779a7e-4546-11e8-8bb5-117de2fb57ea.png)

And here's kroc:

![kroc](https://user-images.githubusercontent.com/18505570/39081228-4d65afbe-4546-11e8-9cb5-d10f4120fe5e.png)

In each screenshot, I have clicked the `akuliiiii` item to select it, but many themes fail to display the selected item differently.

Can you fix this? If you can't, I can look into this and make a pull request. I really want this fixed soon.

**Edit:** Here's a handy task list. Checking a box means that the theme works ok.

- [x] alt
- [x] aquativo
- [x] arc
- [x] black
- [x] blue
- [x] clam
- [x] classic
- [x] clearlooks
- [x] elegance
- [x] keramic
- [x] keramic_alt
- [x] kroc
- [x] plastik
- [x] radiance
- [x] winxpblue

**Comment by RedFantom** [comment]
![screenshot from 2018-04-21 11-02-35](https://user-images.githubusercontent.com/15170036/39082452-a601468a-4553-11e8-89b0-34e446866816.png)
This seems a bit criminal. I will choose a different `selectfg` color.

**Comment by Akuli** [comment]
Much better, but what about the big white areas in the screenshots? black looks like this now:

![asdasd](https://user-images.githubusercontent.com/18505570/39082930-bbee0ba8-4563-11e8-98c0-987aaf696384.png)

I think the white area is a bit weird for a theme named `black`.

**Comment by RedFantom** [comment]
I'm not sure whether I can change that. I have not noticed it being changed in other themes. I will look into it later today.

**Comment by Akuli** [comment]
Awesome, this is good enough for now! :)

**Comment by RedFantom** [comment]
Yes, I would rather make those changes, if they're even a possibility, in a different branch.

**Comment by Poulpy** [comment]
I'm trying to use the breeze theme, however when clicking on a Treeview item, there's no highlighting (as shown below).

Is there a way to fix this ?



![image](https://user-images.githubusercontent.com/33195525/77238251-dd646280-6bce-11ea-8a94-7c34a0ddb2cc.png)

**Comment by RedFantom** [comment]
There is a way to fix it indeed, as you have already seen in MaxPerl/ttk-Breeze#4 . I will commit the change directly to the master branch. Thank you for reporting this!
