### ISSUE TITLE
Themes not showing except for radiance

### ISSUE THREAD

**Issue by JJCbr** [TkinterEP/ttkthemes#65]
Dear RedFantom,

Thanks a lot for ttkthemes it is a great resource that I am looking forward to using. I am using Python 3.7, tkinter 8.6.9, Windows 10 and have implimented ttkthemes by importing and switching my call to tkinter root:

from ttkthemes import ThemedTk
root = ThemedTk(theme="radiance") #ttk.Tk()

This works nicely with 'radiance', but changing to any other theme (i.e. 'blue', 'kroc', 'clearlooks') does not seem to work. If you have any thoughts on this it would be much appreciated and please let me know if you need anymore information.

**Comment by Akuli** [comment]
What do you mean with "does not seem to work"? What code did you try? Did you get an error message?

**Comment by JJCbr** [comment]
Dear Akuli,

Thanks a lot for your response, apologies for the lack of detail in my initial question. I meant that no formatting appears to take place for any theme other than radiance, with themes such as 'black' looking similar to default (please see attached image). I have also included an example code that captures the main elements from the project I am working on, please let me know if you need anymore information, many thanks.

`import tkinter as ttk
from ttkthemes import ThemedTk
import random

class buttonMethods:
    def __init__(self):
        self.openwindowone()
        self.shownumber()

    def openwindowone():
        global openWindowOne
        openWindowOne = windowOne(myprog.mainframe)

    def shownumber():
        randomInterger = random.randint(0,100)
        openWindowOne.label.configure(text=str(randomInterger))


class mainWindow:
    def __init__(self, master):
        self.mainframe = ttk.Frame(master, width=500, height=500, relief='raised', borderwidth=10)
        self.mainframe.grid(column=0, row=0, sticky='nsew')
        self.openWindowClass = buttonMethods

        button1 = ttk.Button(self.mainframe, text='Window One', command=self.openWindowClass.openwindowone, anchor='center')
        button1.grid(column=0, row=0, sticky='nsew', padx=20, pady=20)

        button2 = ttk.Button(self.mainframe, text='Window Two')
        button2.grid(column=1, row=0, sticky='nsew', padx=20, pady=20) #placeholder

        label1 = ttk.Label(self.mainframe, text='Label', font=('Arial',12), anchor='center', bg='white')
        label1.grid(row=2, column=0, columnspan=2, sticky='nsew', padx=10, pady=10)


class windowOne:
    def __init__(self, master):
        self.window = ttk.Toplevel(master, relief='sunken')
   #     self.frame = ttk.Frame(self.window, column=0, row =0, sticky='nsew')
        self.window.grid_rowconfigure(0, weight=1)
        self.window.grid_rowconfigure(1, weight=3)
        self.window.grid_columnconfigure(0, weight=1)

        self.text = ttk.StringVar(); self.text = 'Number will show here'
        self.label = ttk.Label(self.window, text=self.text, bg='white', font=('Arial', 12, 'bold'), fg='black', bd=2, width=20)
        self.label.grid(row=1, column=0, rowspan=2, sticky='nsew', padx=10, pady=10)
        self.label.grid_propagate(False)

        var = ttk.IntVar(); var.set(1)
        self.radiobuttonBlack = ttk.Radiobutton(self.window, text='Click for Black Text', variable=var, value=1,  command=lambda: self.label.config(fg='black'))
        self.radiobuttonBlack.grid(row=1, column=1, padx=10, pady=10, sticky='nsew')
        self.radiobuttonRed = ttk.Radiobutton(self.window, text= 'Click for Red Text', variable=var, value=2, command=lambda: self.label.config(fg='red'))
        self.radiobuttonRed.grid(row=2, column=1, padx=10, pady=10, sticky='nsew')

        self.Button = ttk.Button(self.window, text='Show A Number', command=buttonMethods.shownumber)
        self.Button.grid(column=0, row=0, columnspan=2, padx=10, pady=10, sticky='ew')

root =  ThemedTk(theme='radiance')
root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)
root.resizable(False, False)
myprog = mainWindow(root)
root.mainloop()
![ttkthemes](https://user-images.githubusercontent.com/55797454/71315387-abb6f080-2453-11ea-9ba7-efed23d1c788.png)
`

**Comment by RedFantom** [comment]
To find the problem, look no further than the import at the top of the file of your example code. It says:
```python
import tkinter as ttk
```

`ttk` is actually a submodule in the `tkinter` package. In order to fix your problem, change the line to:

```python
import tkinter as tk
from tkinter import ttk
```
And in addition change the `ttk.Toplevel` (which does not exist) to a `tk.Toplevel`. Only then will your widgets by actual widgets from the `ttk` module and thus the themeing be applied as shown in the example images in the documentation.

**Comment by JJCbr** [comment]
Thanks a lot for your help RedFantom, works perfect had has led to some very useful reading on the differences between tk and ttk (of which I previously did not know there was a distinction. Thanks a lot for your help and maintaing this great resource.

**Comment by RedFantom** [comment]
No problem at all!
