### ISSUE TITLE
[ Question ] Are any changes made to my tkinter installation itself?

### ISSUE THREAD

**Issue by PySimpleGUI** [TkinterEP/ttkthemes#69]
Pardon my ignorance and my lack of proper research.... yet.  I'll get to it for sure.  

I'm highly intrigued and would like to eventually perhaps officially integrate with your project.  The results I've seen from one of my package's users was pretty remarkable.  

What I would like to understand is if any part of the tkinter installation or its files are modified when ttkthemes is installed or executed.  I don't feel like I can take the chance just yet and give things a go until I get better educated.

PySimpleGUI wraps tkinter and does a lot of work on behalf of the user.  The result is the ability to quickly and easily make GUI programs for tkinter, Qt, WxPython and Remi.  tkinter gets the majority of the focus however.

Thank you for your time... I really hope to be able to use your code in a bigger way in the near future!  I just want to make sure I don't do anything potentially harmful to my environment due to my lack of knowledge.

**Comment by Akuli** [comment]
>What I would like to understand is if any part of the tkinter installation or its files are modified when ttkthemes is installed or executed.

ttkthemes doesn't work like that. Ttk itself supports themes already, and ttkthemes essentially just gives it more themes to choose from.

I have added ttkthemes to an existing ttk tkinter project, and since PySimpleGUI already uses ttk widgets, that's exactly what you want to do. If you don't want to change the code that creates the root window (which I didn't), you need to create a `ttkthemes.ThemedStyle` object and `set_theme()` with that, and it should just work.

**Comment by PySimpleGUI** [comment]
Thank you so much for the rapid reply!  Very helpful info.  Really appreciate the help and what you're doing for the tkinter world.

**Comment by RedFantom** [comment]
Thank you for your question! Akuli answered it more clearly than I probably could have, as I have never used `PySimpleGUI`. If you do want to integrate with this project, please let me know if you have any questions or are looking to work together.

**Comment by PySimpleGUI** [comment]
One of my users is using it and they didn't have to do anything except the parameter in my `Window` object call.  There was nothing else that changed.  It's weird.  That means something in the tkinter universe changed.  I'll try it in my Linux build today.  I can't risk my Windows setup at the moment.  There's just too much going on.

I think I understand what you're saying that ttk is simply being provided more themes. My question/point /observation is that since nothing changed in my source code except which theme is chosen, that means something in the tkinter folder/source tree / universe changed that gave it these additional themes.

I'm sorry, I'm not meaning to argue or continue to show my ignorance.  I'll figure it out eventually.  I'm really looking forward to using them. I just have get myself enough time to properly educate myself.  

I appreciate your time and patience in answering this issue and **certainly** thank you for providing this to tkinter users.

It makes me sad to see people knocking tkinter on Reddit as being "ugly".  What's "ugly" is their in ability to learn how to properly design a nice looking window.  If they don't have a tool that does it all for them at the push of a button, then they think it's ugly.  We've got Jiffy Lube workers now instead of BMW Engine Designers that are using our work.

Anyway, thank you again.... I'll post my results soon-ish 👍

**Comment by Akuli** [comment]
Another reason why people think of tkinter as ugly might be that they are not aware of ttk.
