### ISSUE TITLE
Can i set a theme for tkinter Listbox

### ISSUE THREAD

**Issue by leonarduz13** [TkinterEP/ttkthemes#73]
Listbox is not a themed widget, so it looks ugly in all my apps. Is there any way to change its theme?

**Comment by RedFantom** [comment]
You are correct in noting that the `tk.Listbox` is not a themed widget, as it is not part of the `ttk` widget set. Therefore, you cannot theme it. You may be able to change its default colours to match the applied theme, but that's where the options end.

I'd recommend changing from the `Listbox` to the `Treeview` widget. It is more versatile but can also be used where the `Listbox` is used. It may require a few more lines of code to configure, but it's not a difficult widget to use.
