### ISSUE TITLE
Maximum recursion depth exceeded when using toplevel=True option

### ISSUE THREAD

**Issue by kev-a-s** [TkinterEP/ttkthemes#74]
`__init__toplevel` should be set before potential call to `set_theme`. `set_theme` can call `_setup_toplevel_hook`, which will overwrite `Toplevel.__init__` before it has been saved. This leads to infinite recursion when a `Toplevel` is created.

https://github.com/TkinterEP/ttkthemes/blob/82b848b7d3ca269c843df1b418b9132c744cc1da/ttkthemes/themed_tk.py#L66-L67

**Comment by Akuli** [comment]
does this have something to do with the `__getattr__` in `tkinter.Tk`?

**Comment by kev-a-s** [comment]
No. I should have given steps to reproduce.
`root = ThemedTk(theme='dark', toplevel=True)
win = Toplevel(master=root)`

Can be avoided by doing a config call after init instead of passing toplevel = True to constructor.

**Comment by RedFantom** [comment]
Hello! Thank you for opening this issue. This indeed appears to be a bug. Could you try the fix I applied in the `fix` branch?

**Comment by kev-a-s** [comment]
That works.
