### ISSUE TITLE
License text for themes

### ISSUE THREAD

**Issue by olebole** [TkinterEP/ttkthemes#77]
Hi,

I am currently [packaging the "ttkthemes" for Debian](https://bugs.debian.org/974636). When looking through the individual licenses, I found in many of them a statement that restricts the right for US governmental use:

> GOVERNMENT USE: If you are acquiring this software on behalf of the U.S. government, the Government shall have only "Restricted Rights" in the software and related documentation as defined in the Federal Acquisition Regulations (FARs) in Clause 52.227.19 (c) (2). If you are acquiring the software on behalf of the Department of Defense, the software shall be classified as "Commercial Computer Software" and the Government shall have only "Restricted Rights" as defined in Clause 252.227-7013 (c) (1) of DFARs. Notwithstanding the foregoing, the authors grant the U.S. Government and others acting in its behalf  permission to use and distribute the software in accordance with the terms specified in this license.

The problem with that statement is that it contradicts the "non discrimination" clauses of [Open Source](https://opensource.org/osd-annotated):

> ### 5. No Discrimination Against Persons or Groups
> The license must not discriminate against any person or group of persons.
> ### 6. No Discrimination Against Fields of Endeavor
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the  program from being used in a business, or from being used for genetic research.

Since we have similar rules in our [Debian Free Software Guidelines](https://www.debian.org/social_contract), this means that we can't create a Debian package for ttkthemes, which would be a significant loss. It makes the themes also incompatible with any GPLed software, which does not allow additional restrictions.

What is reason for this restriction, and could it be removed?

Best regards

Ole

**Comment by olebole** [comment]
I just found out that this is the standard Tcl/Tk license, which seems to work in Debian. So, I would withdraw this for the moment, unless out ftp-masters are going to reject the package.

**Comment by RedFantom** [comment]
Thank you for your question! Indeed this is the standard Tcl/Tk license, which I hope will not pose a problem for packaging the project for Debian. However, I feel I should point out that I only gather the themes and thus not the copyright holder on most of them. 

I am not a lawyer, but I have tried to interpret and research the licenses to the best of my ability. The Tcl/Tk License actually specifically allows relicensing, and the [Fedora Project](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Software_License_List) does list the Tcl/Tk License as GNU GPLv2 and v3 compatible, which is what has led me to believe that all these Tcl/Tk Licensed themes can be included in this project and also in GPL software packages. Of course, Fedora is not Debian, but perhaps it can be of use.

Let me know if there's anything else I can do. It always brings me joy to see projects I work on put to use!
