### ISSUE TITLE
Pip installation fails in macOS Big Sur on Apple Silicon

### ISSUE THREAD

**Issue by tcarroll2** [TkinterEP/ttkthemes#79]
I have a brand new MacBook Air that I am trying to install ttkthemes on via pip.  I have python v3.9.1 installed via pyenv.

The error being given is "RuntimeError: This version of ttkthemes does not support Tk 8.5 and earlier. Please install an earlier version."

I do not get this error under Python 3.7.4/3.8 in Big Sur running on an Intel platform.

I have tcl-tk 8.6.11 installed via homebrew.

**Comment by tcarroll2** [comment]
Never mind.  I forgot a step.  I will put this link here for future reference.

You should change the error message to read "This version of ttkthemes does not support Tk 8.5 and earlier. Please install a later version."

[https://github.com/pyenv/pyenv/issues/1375](https://github.com/pyenv/pyenv/issues/1375)

**Comment by RedFantom** [comment]
Well, that's certainly an unfortunate mistake. Thank you for pointing this out, and I'm glad `ttkthemes` also works on Apple Silicon 👍🏻
