### ISSUE TITLE
Cannot use ttkthemes because there's missing scid.tcl

### ISSUE THREAD

**Issue by monicacue** [TkinterEP/ttkthemes#83]
I've tried to use tkkthemes by writing those commands on my app: I'm running Python 3.9 over Windows 10.

```python

import tkinter
from tkinter import *
from tkinter.font import BOLD, Font
from tkinter import ttk
from ttkthemes import themed_tk as tk

app = tk.ThemedTk(theme="breeze")

#Whatever code

app.mainloop()
```

However the terminal sends me the following error, and the app just don't run:

```python
File "C:\Users\user\Documents\Code\Window.py", line 8, in <module>
    app = tk.ThemedTk(theme="breeze")
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ttkthemes\themed_tk.py", line 68, in __init__
    ThemedWidget.__init__(self, self.tk, gif_override)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ttkthemes\_widget.py", line 63, in __init__
    self._load_themes()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ttkthemes\_widget.py", line 73, in _load_themes
    self.tk.call("package", "require", "ttk::theme::scid")
_tkinter.TclError: couldn't read file "C:/Users/user/AppData/Local/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/LocalCache/local-packages/Python39/site-packages/ttkthemes/png/scid/scid.tcl": no such file or directory

```

No matter the content of my app, or what theme I choose, the error is the same always, and it always ask me for the SAME file.  I've tried to enter to the folder that gives me the error to verify that the file "scid.tcl" is installed corrently in my system, and it is! However the error persist.

Thanks!

![problem](https://user-images.githubusercontent.com/85193690/120379644-abc44c80-c2e5-11eb-8615-a5b5fae22bcf.png)

**Comment by Akuli** [comment]
Do you get the error if you run this shorter program?

```python3
import ttkthemes
ttkthemes.ThemedTk(theme="breeze")
```

I tried it. No error for me.

**Comment by syjgino** [comment]
I just tried it. No errors for me.

**Comment by Akuli** [comment]
But this code still errors?

```
import tkinter
from tkinter import *
from tkinter.font import BOLD, Font
from tkinter import ttk
from ttkthemes import themed_tk as tk

app = tk.ThemedTk(theme="breeze")
```

**Comment by syjgino** [comment]
No, no errors for me. The question is from *m**onicacue *though.

**Comment by monicacue** [comment]
> 
> 
> Do you get the error if you run this shorter program?
> 
> ```python
> import ttkthemes
> ttkthemes.ThemedTk(theme="breeze")
> ```
> 
> I tried it. No error for me.

Thanks Akuli!!! That line of code works perfect. The example that is found on documentation (https://ttkthemes.readthedocs.io/en/latest/example.html) or the code that I wrote above, both didn't work at all. As I mentioned before throwed me that error. But now it works.
